"""Shadow-clerk daemon: ダッシュボード HTML テンプレート"""

from shadow_clerk._daemon_dashboard_css import _CSS_TEMPLATE
from shadow_clerk._daemon_dashboard_js import _JS_TEMPLATE

_HTML_TEMPLATE = (
    "<!DOCTYPE html>\n"
    "<html lang=\"ja\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>Shadow-clerk Dashboard</title>\n"
    "<style>\n"
    + _CSS_TEMPLATE
    + "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header>\n"
    "  <label for=\"langSel\" style=\"font-size:12px;color:#aaa;margin-right:2px\">{{i18n:dash.detect_language}}</label><select id=\"langSel\" onchange=\"onLangChange(this.value)\">\n"
    "    <option value=\"auto\">auto</option>\n"
    "    <option value=\"ja\">ja</option>\n"
    "    <option value=\"en\">en</option>\n"
    "    <option value=\"zh\">zh</option>\n"
    "    <option value=\"ko\">ko</option>\n"
    "    <option value=\"fr\">fr</option>\n"
    "    <option value=\"de\">de</option>\n"
    "    <option value=\"es\">es</option>\n"
    "    <option value=\"pt\">pt</option>\n"
    "    <option value=\"ru\">ru</option>\n"
    "  </select>\n"
    "  <span id=\"asrInfo\" style=\"font-size:11px;color:#888\"></span>\n"
    "  <select id=\"fsel\" onchange=\"onSel()\"><option value=\"\">...</option></select><button class=\"toggle\" id=\"btnGoActive\" onclick=\"goActive()\" title=\"Go to active file\" style=\"font-size:13px;padding:2px 4px\">\u2605</button>\n"
    "  <div class=\"g\">\n"
    "    <button class=\"pri\" id=\"btnMeeting\" onclick=\"togMeeting()\">{{i18n:dash.meeting_toggle_start}}</button>\n"
    "    <button id=\"btnTranslate\" onclick=\"togTranslate()\">{{i18n:dash.translate_start}}</button>\n"
    "    <button onclick=\"genSummary()\">{{i18n:dash.summary}}</button>\n"
    "    <button onclick=\"viewSummary()\">{{i18n:dash.view_summary}}</button>\n"
    "  </div>\n"
    "  <div class=\"g\" style=\"margin-left:auto\">\n"
    "    <button class=\"toggle\" id=\"togTR\" onclick=\"cyclePanel()\">T|R</button>\n"
    "    <button onclick=\"openGlossary()\">{{i18n:dash.glossary}}</button>\n"
    "    <button class=\"toggle\" id=\"btnPTT\" onclick=\"togPTT()\" style=\"min-width:auto;padding:2px 6px;font-size:11px\">PTT</button>\n"
    "    <button onclick=\"openCustomCmds()\">{{i18n:dash.custom_commands}}</button>\n"
    "    <button onclick=\"openCfg()\" title=\"{{i18n:dash.settings}}\">\u2699</button>\n"
    "    <button onclick=\"openHelp()\" title=\"{{i18n:dash.help}}\">\u2753</button>\n"
    "  </div>\n"
    "</header>\n"
    "<div id=\"resp\"><div class=\"rh\"><span>LLM Response</span><button class=\"toggle\" onclick=\"hideResp()\">&times;</button></div><div class=\"rb\" id=\"respBody\"></div></div>\n"
    "<main>\n"
    "  <div class=\"panel\" id=\"pnlT\">\n"
    "    <div class=\"ph\"><span>Transcript <button class=\"toggle\" onclick=\"openFileDelModal()\" title=\"{{i18n:dash.delete_file_title}}\" style=\"font-size:12px;margin-left:2px\">\U0001f5d1</button></span><span style=\"display:flex;gap:4px;align-items:center\"><div class=\"sel-actions\" id=\"selActions\"><span class=\"sel-count\" id=\"selCount\"></span><button onclick=\"openBulkDelModal()\" id=\"btnBulkDel\" title=\"{{i18n:dash.delete}}\">\U0001f5d1</button><button onclick=\"openExtractModal()\" id=\"btnExtract\" title=\"{{i18n:dash.extract_meeting_title}}\" style=\"display:none\">\u23f1</button><button class=\"toggle\" onclick=\"deselectAll()\">&times;</button></div><button class=\"toggle\" id=\"btnMuteMic\" onclick=\"togMute('mic')\" title=\"{{i18n:dash.mute_mic}}\">\U0001f3a4</button><button class=\"toggle\" id=\"btnMuteMonitor\" onclick=\"togMute('monitor')\" title=\"{{i18n:dash.mute_monitor}}\">\U0001f50a</button><span id=\"tf\" style=\"font-weight:normal\"></span></span></div>\n"
    "    <div class=\"pc\" id=\"tp\"></div>\n"
    "  </div>\n"
    "  <div class=\"panel\" id=\"pnlR\">\n"
    "    <div class=\"ph\"><span>Translation</span><span style=\"display:flex;gap:4px;align-items:center\"><button class=\"toggle\" onclick=\"regenTranslate()\" title=\"{{i18n:dash.translate_regen}}\">\U0001f504</button><span id=\"rf\" style=\"font-weight:normal\"></span></span></div>\n"
    "    <div class=\"pc\" id=\"rp\"></div>\n"
    "  </div>\n"
    "</main>\n"
    "<div id=\"interim-area\" style=\"display:none; border-top:1px solid var(--border); padding:4px 12px; flex-shrink:0;\">\n"
    "  <div id=\"interim-monitor\" class=\"interim\"></div>\n"
    "  <div id=\"itp\" class=\"interim\"></div>\n"
    "</div>\n"
    "<div id=\"logp\">\n"
    "  <div class=\"ph\" style=\"cursor:pointer\" onclick=\"togLogs()\"><span>Logs</span><span id=\"logArrow\">\u25bc</span></div>\n"
    "  <div id=\"logc\"></div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"cfgModal\" onclick=\"if(event.target===this)closeCfg()\">\n"
    "  <div class=\"modal\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.settings_title}}</span><button onclick=\"closeCfg()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" id=\"cfgBody\"></div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <span class=\"saved\" id=\"cfgSaved\">{{i18n:dash.saved}}</span>\n"
    "      <button onclick=\"closeCfg()\">{{i18n:dash.cancel}}</button>\n"
    "      <button class=\"pri\" onclick=\"saveCfg()\">{{i18n:dash.save}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"glossaryModal\" onclick=\"if(event.target===this)closeGlossary()\">\n"
    "  <div class=\"modal\" style=\"max-width:700px;\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.glossary_title}}</span><button onclick=\"closeGlossary()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;max-height:60vh;overflow-y:auto;\">\n"
    "      <table id=\"glossaryTable\" style=\"width:100%;border-collapse:collapse;font-size:13px;\">\n"
    "        <thead><tr id=\"glossaryHead\"></tr></thead>\n"
    "        <tbody id=\"glossaryBody\"></tbody>\n"
    "      </table>\n"
    "      <div style=\"margin-top:8px;\">\n"
    "        <button onclick=\"glossaryAddRow()\" style=\"font-size:12px;\">{{i18n:dash.add_row}}</button>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <span class=\"saved\" id=\"glossarySaved\">{{i18n:dash.saved}}</span>\n"
    "      <button onclick=\"closeGlossary()\">{{i18n:dash.cancel}}</button>\n"
    "      <button class=\"pri\" onclick=\"saveGlossary()\">{{i18n:dash.save}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"summaryModal\" onclick=\"if(event.target===this)closeSummary()\">\n"
    "  <div class=\"modal\" style=\"max-width:700px;\">\n"
    "    <div class=\"modal-head\"><span id=\"summaryTitle\">{{i18n:dash.summary_title}}</span><button onclick=\"closeSummary()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;max-height:60vh;overflow-y:auto;\">\n"
    "      <div id=\"summaryContent\" style=\"white-space:pre-wrap;font-size:13px;line-height:1.6;\"></div>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <button onclick=\"closeSummary()\">{{i18n:dash.close}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"helpModal\" onclick=\"if(event.target===this)closeHelp()\">\n"
    "  <div class=\"modal\" style=\"max-width:600px;\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.help_title}}</span><span style=\"margin-left:auto;margin-right:8px;\"><a id=\"helpReadmeLink\" href=\"https://github.com/edocode/shadow-clerk#readme\" target=\"_blank\" rel=\"noopener\" style=\"font-size:13px;\">README</a></span><button onclick=\"closeHelp()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;max-height:70vh;overflow-y:auto;font-size:13px;line-height:1.7;\">\n"
    "      <div id=\"helpContent\" style=\"white-space:pre-wrap;\"></div>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <button onclick=\"closeHelp()\">{{i18n:dash.close}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"customCmdModal\" onclick=\"if(event.target===this)closeCustomCmds()\">\n"
    "  <div class=\"modal\" style=\"max-width:700px;\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.custom_commands_title}}</span><button onclick=\"closeCustomCmds()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;max-height:60vh;overflow-y:auto;\">\n"
    "      <table id=\"customCmdTable\" style=\"width:100%;border-collapse:collapse;font-size:13px;\">\n"
    "        <thead><tr><th>{{i18n:dash.custom_cmd_pattern}}</th><th>{{i18n:dash.custom_cmd_action}}</th><th style=\"width:30px\"></th></tr></thead>\n"
    "        <tbody id=\"customCmdBody\"></tbody>\n"
    "      </table>\n"
    "      <div style=\"margin-top:8px;\">\n"
    "        <button onclick=\"customCmdAddRow()\" style=\"font-size:12px;\">{{i18n:dash.add_row}}</button>\n"
    "      </div>\n"
    "      <div style=\"margin-top:12px;font-size:12px;color:var(--muted);line-height:1.5;\">{{i18n:dash.custom_cmd_hint}}</div>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <span class=\"saved\" id=\"customCmdSaved\">{{i18n:dash.saved}}</span>\n"
    "      <button onclick=\"closeCustomCmds()\">{{i18n:dash.cancel}}</button>\n"
    "      <button class=\"pri\" onclick=\"saveCustomCmds()\">{{i18n:dash.save}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"bulkDelModal\" onclick=\"if(event.target===this)closeBulkDelModal()\">\n"
    "  <div class=\"modal\" style=\"max-width:600px;\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.bulk_delete_title}}</span><button onclick=\"closeBulkDelModal()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;max-height:50vh;overflow-y:auto;font-size:13px;\">\n"
    "      <div id=\"bulkDelRangeOpt\" style=\"display:none;margin-bottom:8px;\">\n"
    "        <label class=\"extract-option\"><input type=\"radio\" name=\"bulkDelMode\" value=\"range\"><span class=\"eo-label\">{{i18n:dash.bulk_delete_range}}</span></label>\n"
    "        <label class=\"extract-option\"><input type=\"radio\" name=\"bulkDelMode\" value=\"selected\"><span class=\"eo-label\">{{i18n:dash.bulk_delete_selected}}</span></label>\n"
    "      </div>\n"
    "      <div style=\"margin-bottom:8px;font-weight:600;color:var(--muted);\">{{i18n:dash.delete_line_transcript}}</div>\n"
    "      <div class=\"del-lines-list\" id=\"bulkDelTranscript\"></div>\n"
    "      <div style=\"margin-bottom:8px;font-weight:600;color:var(--muted);\">{{i18n:dash.delete_line_translation}}</div>\n"
    "      <div class=\"del-lines-list\" id=\"bulkDelTranslation\" style=\"color:var(--muted);\"></div>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <button onclick=\"closeBulkDelModal()\">{{i18n:dash.cancel}}</button>\n"
    "      <button class=\"dan\" onclick=\"doBulkDel()\">{{i18n:dash.delete}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"extractModal\" onclick=\"if(event.target===this)closeExtractModal()\">\n"
    "  <div class=\"modal\" style=\"max-width:500px;\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.extract_meeting_title}}</span><button onclick=\"closeExtractModal()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;font-size:13px;\">\n"
    "      <div id=\"extractRange\" style=\"margin-bottom:8px;color:var(--muted);\"></div>\n"
    "      <div id=\"extractLineCount\" style=\"margin-bottom:12px;color:var(--muted);\"></div>\n"
    "      <label class=\"extract-option\"><input type=\"radio\" name=\"extractTarget\" value=\"new\" checked><span class=\"eo-label\">{{i18n:dash.extract_meeting_new}}</span></label>\n"
    "      <label class=\"extract-option\"><input type=\"radio\" name=\"extractTarget\" value=\"existing\"><span class=\"eo-label\">{{i18n:dash.extract_meeting_existing}}</span><select id=\"extractExistingSel\" disabled onclick=\"event.stopPropagation()\"></select></label>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <button onclick=\"closeExtractModal()\">{{i18n:dash.cancel}}</button>\n"
    "      <button class=\"pri\" onclick=\"doExtractMeeting()\">{{i18n:dash.extract_meeting_create}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal-overlay\" id=\"fileDelModal\" onclick=\"if(event.target===this)closeFileDelModal()\">\n"
    "  <div class=\"modal\" style=\"max-width:500px;\">\n"
    "    <div class=\"modal-head\"><span>{{i18n:dash.delete_file_title}}</span><button onclick=\"closeFileDelModal()\">&times;</button></div>\n"
    "    <div class=\"modal-body\" style=\"display:block;font-size:13px;\">\n"
    "      <div style=\"margin-bottom:8px;color:var(--muted);\">{{i18n:dash.delete_file_desc}}</div>\n"
    "      <div class=\"del-lines-list\" id=\"fileDelList\"></div>\n"
    "    </div>\n"
    "    <div class=\"modal-foot\">\n"
    "      <button onclick=\"closeFileDelModal()\">{{i18n:dash.cancel}}</button>\n"
    "      <button class=\"dan\" onclick=\"doFileDel()\">{{i18n:dash.delete}}</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<script>\n"
    + _JS_TEMPLATE
    + "</script>\n"
    "</body>\n"
    "</html>\n"
)
